language: ruby
sudo: required
cache: bundler
services: docker
before_script: mkdir debs && chmod 777 debs
env:
    - TRAVIS_ARCH=aarch64
    - TRAVIS_ARCH=arm
    - TRAVIS_ARCH=i686
    - TRAVIS_ARCH=x86_64
