# See documentation at
# https://github.com/rust-lang/rust/blob/master/config.example.toml

[llvm]
link-shared = true

[build]
host = ["@CARGO_TARGET_NAME@"]
target = [
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "i686-linux-android",
    "x86_64-linux-android",
    "wasm32-unknown-unknown",
    "wasm32-wasi",
]
rustc = "@RUSTC@"
cargo = "@CARGO@"
python = "python3"
extended = true
tools = [
    "cargo",
    "clippy",
    "rustdoc",
    "rustfmt",
    "rust-analyzer-proc-macro-srv",
    "analysis",
    "src",
    "rust-demangler",
]
sanitizers = false
android-ndk = "@TERMUX_STANDALONE_TOOLCHAIN@"

[install]
prefix = "@TERMUX_PREFIX@"
sysconfdir = "etc"

[rust]
optimize = true
debug = false
codegen-units = 0
jemalloc = false
channel = "stable"
rpath = false

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config-17"

[target.aarch64-linux-android]
llvm-config = "@TERMUX_PREFIX@/bin/llvm-config"
profiler = true

[target.armv7-linux-androideabi]
llvm-config = "@TERMUX_PREFIX@/bin/llvm-config"
profiler = true

[target.i686-linux-android]
llvm-config = "@TERMUX_PREFIX@/bin/llvm-config"
profiler = true

[target.x86_64-linux-android]
llvm-config = "@TERMUX_PREFIX@/bin/llvm-config"
profiler = true

[target.wasm32-wasi]
wasi-root = "@TERMUX_PREFIX@/share/wasi-sysroot"

[target.wasm32-wasip1]
wasi-root = "@TERMUX_PREFIX@/share/wasi-sysroot"

[target.wasm32-wasip2]
wasi-root = "@TERMUX_PREFIX@/share/wasi-sysroot"

[dist]
src-tarball = false
compression-formats = ["gz"]
#missing-tools = true
