# See documentation at
# https://github.com/rust-lang/rust/blob/master/config.toml.example

[llvm]
link-shared = true

[build]
host = ["@triple@"]
target = ["@triple@", "wasm32-unknown-unknown"]
rustc = "@RUSTC@"
cargo = "@CARGO@"

python = "python2.7"
extended = true
sanitizers = false

#tools = ["cargo", "analysis", "clippy-driver" ]
tools = ["cargo", "rls", "clippy", "rustfmt", "analysis", "src"]

[install]
prefix = "@TERMUX_PREFIX@"
sysconfdir = "etc"

[rust]
optimize = true
debug = false
codegen-units = 0
jemalloc = false
channel = "stable"
rpath = false

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config-12"

[target.@triple@]
android-ndk = "@TERMUX_STANDALONE_TOOLCHAIN@"
llvm-config = "@TERMUX_PREFIX@/bin/llvm-config"
ar = "llvm-ar"

[dist]
src-tarball = false
#missing-tools = true
