[build]
build = "x86_64-unknown-linux-gnu"
host = [ "@RUST_TARGET_TRIPLE@" ]
target = [ '@RUST_TARGET_TRIPLE@', 'wasm32-unknown-unknown' ]
docs = false
extended = true
rustc = '@RUSTC@'
cargo = '@CARGO@'
tools = ["cargo", "src"]

[install]
prefix = "@RUST_PREFIX@"

[llvm]
link-shared = true
skip-rebuild = true

[rust]
channel = "nightly"
optimize-tests = false
codegen-tests = false
deny-warnings = false

[target.wasm32-unknown-unknown]

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config-12"

[target.@RUST_TARGET_TRIPLE@]
android-ndk = "@TERMUX_STANDALONE_TOOLCHAIN@"
llvm-config = "@TERMUX_PREFIX@/bin/llvm-config"
ar = "llvm-ar"

#jemalloc = "/path/to/jemalloc/libjemalloc_pic.a"
[dist]
missing-tools = true
